version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-minor-patch:
        dependency-type: development
        update-types: ['minor', 'patch']
    ignore:
      - dependency-name: typescript
      - dependency-name: ts-morph
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
