import { rmSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Rule } from 'eslint';
import { RuleTester } from 'eslint';
import tsParser from '@typescript-eslint/parser';
import { afterAll, describe, expect, it } from 'vitest';
import {
  emitRuleArtifacts,
  evaluateGate,
  generateRuleArtifacts,
  ROLE_PATTERNS,
} from '../../src/index.js';
import type { DetectedPattern, PatternConfig } from '../../src/index.js';

// Wire ESLint's RuleTester to vitest (no global describe/it without `globals: true`).
const hooks = RuleTester as unknown as {
  afterAll: typeof afterAll;
  describe: typeof describe;
  it: typeof it;
  itOnly: typeof it.only;
};
hooks.afterAll = afterAll;
hooks.describe = describe;
hooks.it = it;
hooks.itOnly = it.only;

const here = path.dirname(fileURLToPath(import.meta.url));
const generatedDir = path.join(here, '__generated__');

const AP002: PatternConfig = {
  id: 'AP-002',
  name: 'no-ui-layer-in-server-entry',
  description:
    'A Next.js App Router server-entry file must not import from the components/ (UI) layer.',
  roles: ['ROUTE_HANDLER', 'API_HANDLER', 'TRPC_ROUTER', 'CONTROLLER', 'SERVER_ACTION'],
  forbidden: [/(^|\/)@?\/?components(\/|$)/, /(^|\/)components\//],
};

// A realistic DetectedPattern result (matches the scored inbox-zero run: 216/217, 1 violation).
const gate = evaluateGate({ roleFileCount: 217, violatingFileCount: 1, roleConfidence: 0.94 });
const RESULT: DetectedPattern = {
  id: AP002.id,
  name: AP002.name,
  description: AP002.description,
  roles: AP002.roles,
  stats: {
    roleFileCount: 217,
    conformingFileCount: 216,
    violatingFileCount: 1,
    ratio: gate.conditions.ratio.value,
    roleConfidence: gate.conditions.roleConfidence.value,
  },
  gate,
  violations: [
    {
      file: 'app/api/chat/route.ts',
      specifier: '@/components/assistant-chat/helpers',
      leaf: 'components/assistant-chat/helpers.ts',
    },
  ],
  infraCaution: false,
  infraExceptions: [],
};

// Emit the artifacts and load the generated rule from disk (top level: RuleTester.run below builds
// its own suite and cannot be nested inside an it()).
rmSync(generatedDir, { recursive: true, force: true });
const ruleDir = emitRuleArtifacts(AP002, RESULT, generatedDir, 'test provenance');
const ruleFile = path.join(ruleDir, `${AP002.name}.ts`);
const generatedRule = ((await import(pathToFileURL(ruleFile).href)) as { default: Rule.RuleModule })
  .default;

afterAll(() => rmSync(generatedDir, { recursive: true, force: true }));

describe('rule generator — artifacts', () => {
  it('emits all four artifacts with the evidence attached', () => {
    const { files } = generateRuleArtifacts(AP002, RESULT, 'p');
    expect(files.rule).toContain('GENERATED BY ARCHPRINT');
    expect(files.card).toContain('99.5%'); // the inferred conformance ratio
    expect(files.card).toContain('app/api/chat/route.ts'); // the one exception, disclosed
    expect(files.card).toContain('Enforcement scope and limitations'); // honest boundaries disclosed
    expect(files.passingFixture).not.toContain('components');
    expect(files.failingFixture).toContain('@/components/assistant-chat/helpers');
  });

  it('embeds the classifier role patterns verbatim (single source, no drift)', () => {
    const { files } = generateRuleArtifacts(AP002, RESULT, 'p');
    // Every server-entry role's pattern and every non-entry role's pattern comes from ROLE_PATTERNS,
    // so a future classifier change cannot silently diverge from the emitted rule.
    for (const [role, pattern] of ROLE_PATTERNS) {
      if (role === 'COMPONENT') continue; // .tsx handled separately in the rule
      expect(files.rule).toContain(pattern.source);
    }
  });
});

const ruleTester = new RuleTester({
  languageOptions: { parser: tsParser, ecmaVersion: 2022, sourceType: 'module' },
});

ruleTester.run(AP002.name, generatedRule, {
  valid: [
    {
      name: 'route handler with no UI import',
      filename: 'app/api/example/route.ts',
      code: `import { NextResponse } from 'next/server';\nimport { getUser } from '@/utils/user';\nexport async function GET() { return NextResponse.json(await getUser()); }`,
    },
    {
      name: 'a component may import components (not a server-entry)',
      filename: 'components/Chat.tsx',
      code: `import { Helper } from '@/components/assistant-chat/helpers';\nexport const Chat = () => Helper;`,
    },
    {
      // Classifier parity: a "use server" file under /db/ is DATA_ACCESS, out of the detector's scope,
      // so the rule must not treat it as server-entry (would otherwise be a false positive vs inference).
      name: 'a "use server" data-access module is out of scope (not flagged)',
      filename: 'lib/db/send.ts',
      code: `'use server';\nimport { tpl } from '@/components/email';\nexport async function send() { return tpl; }`,
    },
    {
      // Documented limitation: specifier-level enforcement misses an alias that resolves to a component
      // without "components" in the specifier. The detector would flag this; the rule does not.
      name: 'alias that hides the components path is a known false negative (not flagged)',
      filename: 'app/api/foo/route.ts',
      code: `import { helper } from '@/lib/shared-ui';\nexport async function GET() { return helper; }`,
    },
  ],
  invalid: [
    {
      name: 'route handler importing the components/ layer',
      filename: 'app/api/chat/route.ts',
      code: `import { NextResponse } from 'next/server';\nimport { convertToUIMessages } from '@/components/assistant-chat/helpers';\nexport async function POST() { return NextResponse.json(convertToUIMessages([])); }`,
      errors: [{ messageId: 'forbidden' }],
    },
    {
      name: 'a "use server" action importing the components/ layer',
      filename: 'utils/actions/send.ts',
      code: `'use server';\nimport { render } from '@/components/email/template';\nexport async function send() { return render(); }`,
      errors: [{ messageId: 'forbidden' }],
    },
  ],
});
