import { rmSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Rule } from 'eslint';
import { RuleTester } from 'eslint';
import tsParser from '@typescript-eslint/parser';
import { afterAll, describe, expect, it } from 'vitest';
import {
  emitRuleArtifacts,
  evaluateGate,
  generateRuleArtifacts,
  ROLE_PATTERNS,
} from '../../src/index.js';
import type { DetectedPattern, PatternConfig } from '../../src/index.js';

const hooks = RuleTester as unknown as {
  afterAll: typeof afterAll;
  describe: typeof describe;
  it: typeof it;
  itOnly: typeof it.only;
};
hooks.afterAll = afterAll;
hooks.describe = describe;
hooks.it = it;
hooks.itOnly = it.only;

const here = path.dirname(fileURLToPath(import.meta.url));
const generatedDir = path.join(here, '__generated__');

const AP002: PatternConfig = {
  id: 'AP-002',
  name: 'no-ui-layer-in-server-entry',
  description:
    'A Next.js App Router server-entry file must not import from the components/ (UI) layer.',
  roles: ['ROUTE_HANDLER', 'API_HANDLER', 'TRPC_ROUTER', 'CONTROLLER', 'SERVER_ACTION'],
  forbidden: [/(^|\/)@?\/?components(\/|$)/, /(^|\/)components\//],
};

const gate = evaluateGate({ roleFileCount: 217, violatingFileCount: 1, roleConfidence: 0.94 });
const RESULT: DetectedPattern = {
  id: AP002.id,
  name: AP002.name,
  description: AP002.description,
  roles: AP002.roles,
  stats: {
    roleFileCount: 217,
    conformingFileCount: 216,
    violatingFileCount: 1,
    ratio: gate.observedConformance,
    roleConfidence: gate.conditions.roleConfidence.value,
  },
  gate,
  violations: [
    {
      file: 'app/api/chat/route.ts',
      specifier: '@/components/assistant-chat/helpers',
      leaf: 'components/assistant-chat/helpers.ts',
    },
  ],
  infraCaution: false,
  infraExceptions: [],
};

rmSync(generatedDir, { recursive: true, force: true });
const ruleDir = emitRuleArtifacts(AP002, RESULT, generatedDir, 'test provenance');
const ruleFile = path.join(ruleDir, `${AP002.name}.ts`);
const generatedRule = ((await import(pathToFileURL(ruleFile).href)) as { default: Rule.RuleModule })
  .default;

afterAll(() => rmSync(generatedDir, { recursive: true, force: true }));

describe('rule generator — artifacts', () => {
  it('emits all four artifacts with the evidence attached', () => {
    const { files } = generateRuleArtifacts(AP002, RESULT, 'p');
    expect(files.rule).toContain('GENERATED BY ARCHPRINT');
    expect(files.card).toContain('99.5%');
    expect(files.card).toContain('app/api/chat/route.ts');
    expect(files.card).toContain('Enforcement scope and limitations');
    expect(files.passingFixture).not.toContain('components');
    expect(files.failingFixture).toContain('@/components/assistant-chat/helpers');
  });

  it('embeds the classifier role patterns verbatim (single source, no drift)', () => {
    const { files } = generateRuleArtifacts(AP002, RESULT, 'p');
    for (const [role, patterns] of ROLE_PATTERNS) {
      if (role === 'COMPONENT') continue;
      for (const pattern of patterns) expect(files.rule).toContain(pattern.source);
    }
  });

  it('renders a rule without the "use server" branch and without an exception section', () => {
    const config: PatternConfig = {
      id: 'AP-009',
      name: 'no-x-in-route',
      description: 'x',
      roles: ['ROUTE_HANDLER'],
      forbidden: [/(^|\/)x(\/|$)/],
    };
    const gate = evaluateGate({ roleFileCount: 30, violatingFileCount: 0, roleConfidence: 0.95 });
    const result: DetectedPattern = {
      id: config.id,
      name: config.name,
      description: config.description,
      roles: config.roles,
      stats: {
        roleFileCount: 30,
        conformingFileCount: 30,
        violatingFileCount: 0,
        ratio: gate.observedConformance,
        roleConfidence: gate.conditions.roleConfidence.value,
      },
      gate,
      violations: [],
      infraCaution: false,
      infraExceptions: [],
    };
    const { files } = generateRuleArtifacts(config, result);
    expect(files.rule).not.toContain('hasUseServerDirective(context)');
    expect(files.card).not.toContain('The one exception');
  });
});

const ruleTester = new RuleTester({
  languageOptions: { parser: tsParser, ecmaVersion: 2022, sourceType: 'module' },
});

ruleTester.run(AP002.name, generatedRule, {
  valid: [
    {
      name: 'route handler with no UI import',
      filename: 'app/api/example/route.ts',
      code: `import { NextResponse } from 'next/server';\nimport { getUser } from '@/utils/user';\nexport async function GET() { return NextResponse.json(await getUser()); }`,
    },
    {
      name: 'a component may import components (not a server-entry)',
      filename: 'components/Chat.tsx',
      code: `import { Helper } from '@/components/assistant-chat/helpers';\nexport const Chat = () => Helper;`,
    },
    {
      name: 'a "use server" data-access module is out of scope (not flagged)',
      filename: 'lib/db/send.ts',
      code: `'use server';\nimport { tpl } from '@/components/email';\nexport async function send() { return tpl; }`,
    },
    {
      name: 'alias that hides the components path is a known false negative (not flagged)',
      filename: 'app/api/foo/route.ts',
      code: `import { helper } from '@/lib/shared-ui';\nexport async function GET() { return helper; }`,
    },
  ],
  invalid: [
    {
      name: 'route handler importing the components/ layer',
      filename: 'app/api/chat/route.ts',
      code: `import { NextResponse } from 'next/server';\nimport { convertToUIMessages } from '@/components/assistant-chat/helpers';\nexport async function POST() { return NextResponse.json(convertToUIMessages([])); }`,
      errors: [{ messageId: 'forbidden' }],
    },
    {
      name: 'a "use server" action importing the components/ layer',
      filename: 'utils/actions/send.ts',
      code: `'use server';\nimport { render } from '@/components/email/template';\nexport async function send() { return render(); }`,
      errors: [{ messageId: 'forbidden' }],
    },
  ],
});
