import { mkdirSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { ROLE_PATTERNS } from '../scanner/role-classifier.js';
import type { DetectedPattern } from '../detector/pattern-detector.js';
import type { PatternConfig } from '../detector/pattern-detector.js';

export interface RuleArtifacts {
  ruleName: string;
  files: { rule: string; card: string; passingFixture: string; failingFixture: string };
}

const asRegexArray = (sources: readonly string[]): string =>
  `[${sources.map((source) => `/${source}/`).join(', ')}]`;

const PASSING_IMPORTS = ['next/server', '@/utils/user'] as const;

const withoutFullStop = (text: string): string => text.replace(/\.$/, '');

const isForbidden = (config: PatternConfig, specifier: string): boolean =>
  config.forbidden.some((pattern) => pattern.test(specifier));

function forbiddenSpecifier(config: PatternConfig, result: DetectedPattern): string {
  const candidates = [
    ...result.violations.map((violation) => violation.specifier),
    ...(config.examples ?? []),
  ];
  const specifier = candidates.find((candidate) => isForbidden(config, candidate));
  if (specifier === undefined) {
    throw new Error(
      `${config.id}: no known import matches its forbidden patterns, so its failing fixture cannot be written.`,
    );
  }
  return specifier;
}

function assertPassingFixtureAllowed(config: PatternConfig): void {
  const clash = PASSING_IMPORTS.find((specifier) => isForbidden(config, specifier));
  if (clash !== undefined) {
    throw new Error(
      `${config.id}: its forbidden patterns match "${clash}", so its passing fixture would fail.`,
    );
  }
}

function renderRule(config: PatternConfig, result: DetectedPattern): string {
  const entryPatterns = config.roles
    .flatMap((role) => ROLE_PATTERNS.get(role) ?? [])
    .map((pattern) => pattern.source);
  const nonEntryPatterns = [...ROLE_PATTERNS]
    .filter(([role]) => !config.roles.includes(role) && role !== 'COMPONENT')
    .flatMap(([, patterns]) => patterns.map((pattern) => pattern.source));
  const forbidden = config.forbidden.map((marker) => marker.source);
  const includesServerAction = config.roles.includes('SERVER_ACTION');
  const { ratio, roleFileCount, violatingFileCount } = result.stats;
  const conform = (ratio * 100).toFixed(1);

  return `/**
 * @fileoverview ${config.id} ${config.name}: GENERATED BY ARCHPRINT. Do not edit by hand.
 * Inferred from the real import graph: ${roleFileCount - violatingFileCount}/${roleFileCount} request handlers (${conform}%) already follow this.
 * Evidence and provenance: ./${config.name}.md
 */
import type { Rule } from 'eslint';

const SERVER_ENTRY_PATTERNS: readonly RegExp[] = ${asRegexArray(entryPatterns)};
const NAMED_NON_ENTRY: readonly RegExp[] = ${asRegexArray(nonEntryPatterns)};
const FORBIDDEN: readonly RegExp[] = ${asRegexArray(forbidden)};

const normalize = (filePath: string): string => filePath.replace(/\\\\/g, '/');

function hasUseServerDirective(context: Rule.RuleContext): boolean {
  for (const statement of context.sourceCode.ast.body) {
    if (statement.type !== 'ExpressionStatement') break;
    const expression = statement.expression;
    if (expression.type !== 'Literal' || typeof expression.value !== 'string') break;
    if (expression.value === 'use server') return true;
  }
  return false;
}

function isServerEntry(filename: string, context: Rule.RuleContext): boolean {
  const file = normalize(filename);
  if (SERVER_ENTRY_PATTERNS.some((pattern) => pattern.test(file))) return true;
  ${
    includesServerAction
      ? `if (!file.endsWith('.tsx') && !NAMED_NON_ENTRY.some((pattern) => pattern.test(file))) {
    return hasUseServerDirective(context);
  }`
      : `void NAMED_NON_ENTRY;
  void hasUseServerDirective;`
  }
  return false;
}

const rule: Rule.RuleModule = {
  meta: {
    type: 'problem',
    docs: {
      description: ${JSON.stringify(config.description)},
      recommended: false,
    },
    schema: [],
    messages: {
      forbidden: ${JSON.stringify(`${config.id}: ${withoutFullStop(config.description)} (imported "{{specifier}}").`)},
    },
  },
  create(context) {
    const filename = context.filename;
    if (!isServerEntry(filename, context)) return {};
    return {
      ImportDeclaration(node) {
        const specifier = String(node.source.value);
        if (FORBIDDEN.some((pattern) => pattern.test(specifier))) {
          context.report({ node: node.source, messageId: 'forbidden', data: { specifier } });
        }
      },
    };
  },
};

export default rule;
`;
}

function renderCard(
  config: PatternConfig,
  result: DetectedPattern,
  provenance: string,
  failingSpecifier: string,
): string {
  const { roleFileCount, violatingFileCount, ratio, roleConfidence } = result.stats;
  const example = result.violations[0];
  const gate = result.gate.conditions;
  const pass = (ok: boolean): string => (ok ? 'PASS' : 'FAIL');

  return `# ${config.id} \`${config.name}\`

> Generated by Archprint from the repository's real import graph. ${provenance}

## Rule

${config.description}

**Applies to request handlers:** ${config.roles.join(', ')}. A violation is a request handler that
directly imports something matching a forbidden pattern:
${config.forbidden.map((pattern) => `\`/${pattern.source}/\``).join(', ')}. It checks **direct imports** only:
importing a module that itself imports a forbidden target is out of scope.

## Evidence (why Archprint generated this)

| gate condition | value | threshold | result |
|---|---|---|---|
| conformance (95% lower bound) | ${(gate.confidence.value * 100).toFixed(1)}% floor, ${(ratio * 100).toFixed(1)}% observed (${roleFileCount - violatingFileCount}/${roleFileCount}) | >= 90% | ${pass(gate.confidence.pass)} |
| exceptions | ${violatingFileCount} | <= 3 | ${pass(gate.exceptions.pass)} |
| role confidence | ${roleConfidence.toFixed(2)} | >= 0.80 | ${pass(gate.roleConfidence.pass)} |

Status: **${result.gate.status}** (all conditions must pass to auto-generate; the conformance floor is the
Wilson 95% lower bound over ${roleFileCount} observations, so a thin sample cannot auto-generate).
${
  example
    ? `\n## The one exception in the source repo\n\n\`${example.file}\` imports \`${example.specifier}\`. Review whether it is a genuine violation or a legitimate exception before enforcing.`
    : ''
}

## Enforcement scope and limitations (honest boundaries)

This is a lightweight, self-contained ESLint rule. It enforces at the **import-specifier** level, which
is narrower than the graph-based inference that generated it:

- **Alias/barrel false negative:** an import whose text matches no forbidden pattern but resolves to a
  forbidden target (through an alias or a re-exporting barrel) is **not** caught. The detector resolves
  such imports to the file they reach; the rule matches only the import text.
- **Text-match false positive:** an unrelated import whose text happens to match a forbidden pattern is
  flagged too.
- **Request-handler scope:** mirrors the classifier. A file with a \`"use server"\` directive is treated as
  a request handler only when it is otherwise unclassified; named roles (service, repository, worker, db /
  data-access, shared, test) keep their role and are out of scope.

## Fixtures

- \`fixtures/passing.ts\`: a request handler with no forbidden import (rule stays silent).
- \`fixtures/failing.ts\`: a request handler that imports \`${failingSpecifier}\` (rule reports).
`;
}

function renderPassingFixture(config: PatternConfig): string {
  assertPassingFixtureAllowed(config);
  const [server, user] = PASSING_IMPORTS;
  return `// app/api/example/route.ts (PASSING): a request handler with no import ${config.id} forbids.
import { NextResponse } from '${server}';
import { getUser } from '${user}';

export async function GET(): Promise<Response> {
  return NextResponse.json(await getUser());
}
`;
}

function renderFailingFixture(config: PatternConfig, specifier: string): string {
  return `// app/api/example/route.ts (FAILING): a request handler importing "${specifier}", which ${config.id} forbids.
import { NextResponse } from 'next/server';
import * as forbidden from '${specifier}';

export async function GET(): Promise<Response> {
  return NextResponse.json(Object.keys(forbidden));
}
`;
}

export function generateRuleArtifacts(
  config: PatternConfig,
  result: DetectedPattern,
  provenance = '',
): RuleArtifacts {
  const failingSpecifier = forbiddenSpecifier(config, result);
  return {
    ruleName: config.name,
    files: {
      rule: renderRule(config, result),
      card: renderCard(config, result, provenance, failingSpecifier),
      passingFixture: renderPassingFixture(config),
      failingFixture: renderFailingFixture(config, failingSpecifier),
    },
  };
}

export function emitRuleArtifacts(
  config: PatternConfig,
  result: DetectedPattern,
  outDir: string,
  provenance = '',
): string {
  const artifacts = generateRuleArtifacts(config, result, provenance);
  const ruleDir = path.join(outDir, artifacts.ruleName);
  mkdirSync(path.join(ruleDir, 'fixtures'), { recursive: true });
  writeFileSync(path.join(ruleDir, `${artifacts.ruleName}.ts`), artifacts.files.rule);
  writeFileSync(path.join(ruleDir, `${artifacts.ruleName}.md`), artifacts.files.card);
  writeFileSync(path.join(ruleDir, 'fixtures', 'passing.ts'), artifacts.files.passingFixture);
  writeFileSync(path.join(ruleDir, 'fixtures', 'failing.ts'), artifacts.files.failingFixture);
  return ruleDir;
}
