import { mkdirSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { ROLE_PATTERNS } from '../scanner/role-classifier.js';
import type { DetectedPattern } from '../detector/pattern-detector.js';
import type { PatternConfig } from '../detector/pattern-detector.js';

export interface RuleArtifacts {
  ruleName: string;
  files: { rule: string; card: string; passingFixture: string; failingFixture: string };
}

const asRegexArray = (sources: readonly string[]): string =>
  `[${sources.map((source) => `/${source}/`).join(', ')}]`;

/** Render the self-contained ESLint rule (plain ESLint, no @typescript-eslint runtime dependency). */
function renderRule(config: PatternConfig, result: DetectedPattern): string {
  const entryPatterns = config.roles
    .map((role) => ROLE_PATTERNS.get(role)?.source)
    .filter((source): source is string => source !== undefined);
  // Non-entry roles (COMPONENT handled separately as .tsx): a "use server" file matching these keeps
  // its role, mirroring classifyFileWithDirective.
  const nonEntryPatterns = [...ROLE_PATTERNS]
    .filter(([role]) => !config.roles.includes(role) && role !== 'COMPONENT')
    .map(([, pattern]) => pattern.source);
  const forbidden = config.forbidden.map((marker) => marker.source);
  const includesServerAction = config.roles.includes('SERVER_ACTION');
  const { ratio, roleFileCount, violatingFileCount } = result.stats;
  const conform = (ratio * 100).toFixed(1);

  return `/**
 * @fileoverview ${config.id} ${config.name} — GENERATED BY ARCHPRINT. Do not edit by hand.
 * Inferred from the real import graph: ${roleFileCount - violatingFileCount}/${roleFileCount} server-entry files (${conform}%) already follow this.
 * Evidence and provenance: ./${config.name}.md
 */
import type { Rule } from 'eslint';

const SERVER_ENTRY_PATTERNS: readonly RegExp[] = ${asRegexArray(entryPatterns)};
const NAMED_NON_ENTRY: readonly RegExp[] = ${asRegexArray(nonEntryPatterns)};
const FORBIDDEN: readonly RegExp[] = ${asRegexArray(forbidden)};

const normalize = (filePath: string): string => filePath.replace(/\\\\/g, '/');

function hasUseServerDirective(context: Rule.RuleContext): boolean {
  for (const statement of context.sourceCode.ast.body) {
    if (statement.type !== 'ExpressionStatement') break;
    const expression = statement.expression;
    if (expression.type !== 'Literal' || typeof expression.value !== 'string') break;
    if (expression.value === 'use server') return true;
  }
  return false;
}

function isServerEntry(filename: string, context: Rule.RuleContext): boolean {
  const file = normalize(filename);
  if (SERVER_ENTRY_PATTERNS.some((pattern) => pattern.test(file))) return true;
  ${
    includesServerAction
      ? `if (!file.endsWith('.tsx') && !NAMED_NON_ENTRY.some((pattern) => pattern.test(file))) {
    return hasUseServerDirective(context);
  }`
      : `void NAMED_NON_ENTRY;
  void hasUseServerDirective;`
  }
  return false;
}

const rule: Rule.RuleModule = {
  meta: {
    type: 'problem',
    docs: {
      description: ${JSON.stringify(config.description)},
      recommended: false,
    },
    schema: [],
    messages: {
      forbidden:
        '${config.id}: a server-entry file must not import the UI components/ layer (imported "{{specifier}}"). Move shared logic into a non-UI module.',
    },
  },
  create(context) {
    const filename = context.filename;
    if (!isServerEntry(filename, context)) return {};
    return {
      ImportDeclaration(node) {
        const specifier = String(node.source.value);
        if (FORBIDDEN.some((pattern) => pattern.test(specifier))) {
          context.report({ node: node.source, messageId: 'forbidden', data: { specifier } });
        }
      },
    };
  },
};

export default rule;
`;
}

/** Render the rule card: what the rule is, and the evidence that justified generating it. */
function renderCard(config: PatternConfig, result: DetectedPattern, provenance: string): string {
  const { roleFileCount, violatingFileCount, ratio, roleConfidence } = result.stats;
  const example = result.violations[0];
  const gate = result.gate.conditions;
  const pass = (ok: boolean): string => (ok ? 'PASS' : 'FAIL');

  return `# ${config.id} \`${config.name}\`

> Generated by Archprint from the repository's real import graph. ${provenance}

## Rule

${config.description}

**Scope (server-entry roles):** ${config.roles.join(', ')}. Semantics: **direct import** — a violation
is a server-entry file that directly imports the \`components/\` layer. Transitive reach (importing a
module that itself imports a component) is out of scope.

## Evidence (why Archprint generated this)

| gate condition | value | threshold | result |
|---|---|---|---|
| ratio (conforming) | ${(ratio * 100).toFixed(1)}% (${roleFileCount - violatingFileCount}/${roleFileCount}) | >= 90% | ${pass(gate.ratio.pass)} |
| evidence (files) | ${roleFileCount} | >= 20 | ${pass(gate.evidence.pass)} |
| exceptions | ${violatingFileCount} | <= 3 | ${pass(gate.exceptions.pass)} |
| role confidence | ${roleConfidence.toFixed(2)} | >= 0.80 | ${pass(gate.roleConfidence.pass)} |

Status: **${result.gate.status}** (all four conditions must pass to auto-generate).
${
  example
    ? `\n## The one exception in the source repo\n\n\`${example.file}\` imports \`${example.specifier}\`. Review whether it is a genuine violation or a legitimate exception before enforcing.`
    : ''
}

## Enforcement scope and limitations (honest boundaries)

This is a lightweight, self-contained ESLint rule. It enforces at the **import-specifier** level, which
is narrower than the graph-based inference that generated it:

- **Alias/barrel false negative:** an import whose specifier does not contain \`components\` but resolves
  to the UI layer (e.g. \`@/lib/shared-ui\` aliased to a component) is **not** caught. The detector
  resolves such imports to their leaf; the rule does not. A future alias-aware or dependency-cruiser
  emission would close this.
- **External false positive:** a specifier literally containing \`components\` that resolves inside
  \`node_modules\` would be flagged. Not relevant to this repo, but disclosed.
- **Server-entry scope:** mirrors the classifier. A file with a \`"use server"\` directive is treated as
  server-entry only when it is otherwise unclassified; named roles (service, repository, worker, db /
  data-access, shared, test) keep their role and are out of scope.

## Fixtures

- \`fixtures/passing.ts\` — a server-entry file that does not import the UI layer (rule stays silent).
- \`fixtures/failing.ts\` — a server-entry file that imports the UI layer (rule reports).
`;
}

function renderPassingFixture(): string {
  return `// app/api/example/route.ts — PASSING: a route handler with no UI-layer import.
import { NextResponse } from 'next/server';
import { getUser } from '@/utils/user';

export async function GET(): Promise<Response> {
  return NextResponse.json(await getUser());
}
`;
}

function renderFailingFixture(): string {
  return `// app/api/chat/route.ts — FAILING: a route handler importing the components/ (UI) layer.
import { NextResponse } from 'next/server';
import { convertToUIMessages } from '@/components/assistant-chat/helpers';

export async function POST(): Promise<Response> {
  return NextResponse.json(convertToUIMessages([]));
}
`;
}

/** Build the four artifacts for a detected pattern (pure; no filesystem writes). */
export function generateRuleArtifacts(
  config: PatternConfig,
  result: DetectedPattern,
  provenance = '',
): RuleArtifacts {
  return {
    ruleName: config.name,
    files: {
      rule: renderRule(config, result),
      card: renderCard(config, result, provenance),
      passingFixture: renderPassingFixture(),
      failingFixture: renderFailingFixture(),
    },
  };
}

/** Write the four artifacts to `<outDir>/<rule-name>/` and return the directory. */
export function emitRuleArtifacts(
  config: PatternConfig,
  result: DetectedPattern,
  outDir: string,
  provenance = '',
): string {
  const artifacts = generateRuleArtifacts(config, result, provenance);
  const ruleDir = path.join(outDir, artifacts.ruleName);
  mkdirSync(path.join(ruleDir, 'fixtures'), { recursive: true });
  writeFileSync(path.join(ruleDir, `${artifacts.ruleName}.ts`), artifacts.files.rule);
  writeFileSync(path.join(ruleDir, `${artifacts.ruleName}.md`), artifacts.files.card);
  writeFileSync(path.join(ruleDir, 'fixtures', 'passing.ts'), artifacts.files.passingFixture);
  writeFileSync(path.join(ruleDir, 'fixtures', 'failing.ts'), artifacts.files.failingFixture);
  return ruleDir;
}
