export interface BoundaryRule {
  name: string;
  comment: string;
  from: { path: string };
  to: { path: string };
}

const quote = (pattern: string): string => JSON.stringify(pattern);

function renderTest(rule: BoundaryRule): string {
  return [
    `  // ${rule.comment}`,
    `  it(${quote(rule.name)}, async () => {`,
    '    const violations = await filesOfProject()',
    `      .matchingPattern(${quote(rule.from.path)})`,
    '      .shouldNot()',
    '      .dependOnFiles()',
    `      .matchingPattern(${quote(rule.to.path)})`,
    '      .check();',
    '    expect(violations).toEqual([]);',
    '  });',
  ].join('\n');
}

export function renderTsArchTests(rules: readonly BoundaryRule[]): string {
  return [
    '// Generated by archprint. Do not edit by hand; re-run `archprint generate` to refresh.',
    '// Architecture boundary tests for ts-arch. Requires the `tsarch` dev dependency.',
    "import { filesOfProject } from 'tsarch';",
    "import { describe, expect, it } from 'vitest';",
    '',
    "describe('archprint architecture boundaries', () => {",
    rules.map(renderTest).join('\n\n'),
    '});',
    '',
  ].join('\n');
}
